In [47]:
import numpy as np

In [48]:
l=[1,2,3,4]

In [49]:
arr=np.array(l)

In [50]:
arr

array([1, 2, 3, 4])

In [51]:
type(arr)

numpy.ndarray

In [52]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [53]:
np.asarray(l)

array([1, 2, 3, 4])

In [54]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [55]:
np.matrix(l) #by default 2d array

matrix([[1, 2, 3, 4]])

In [56]:
a=np.array(l)

In [57]:
a

array([1, 2, 3, 4])

In [58]:
c=a  #shallow copy

In [59]:
c

array([1, 2, 3, 4])

In [60]:
c[0]=28

In [61]:
c

array([28,  2,  3,  4])

In [62]:
a

array([28,  2,  3,  4])

In [63]:
d=np.copy(a)  #deep copy

In [64]:
d

array([28,  2,  3,  4])

In [65]:
a[1]=40

In [66]:
a

array([28, 40,  3,  4])

In [67]:
d

array([28,  2,  3,  4])

In [68]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [69]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [70]:
iterable=(i*i for i in range(5))

In [71]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [72]:
np.fromstring('123 123', sep=' ')

array([123., 123.])

In [73]:
np.fromstring('4,5', sep=',')

array([4., 5.])

## numpy datatypes

In [74]:
l=[1,2,3,4,5]

In [75]:
arr=np.array(l)

In [76]:
arr

array([1, 2, 3, 4, 5])

In [77]:
arr.ndim

1

In [78]:
l2=[2,3,4],[4,5,6]

In [79]:
arr2=np.array(l2)

In [80]:
arr2

array([[2, 3, 4],
       [4, 5, 6]])

In [81]:
arr2.ndim

2

In [82]:
arr2.size

6

In [83]:
arr

array([1, 2, 3, 4, 5])

In [84]:
arr.shape

(5,)

In [85]:
arr2

array([[2, 3, 4],
       [4, 5, 6]])

In [86]:
arr2.shape

(2, 3)

In [87]:
arr2.dtype

dtype('int32')

In [88]:
list(range((5)))

[0, 1, 2, 3, 4]

In [89]:
list(range((0.1,5)))

TypeError: 'tuple' object cannot be interpreted as an integer

In [ ]:
list(np.arange(2.5,5.5,0.2))

[2.5,
 2.7,
 2.9000000000000004,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.700000000000001,
 3.9000000000000012,
 4.100000000000001,
 4.300000000000002,
 4.500000000000002,
 4.700000000000002,
 4.900000000000002,
 5.100000000000002,
 5.3000000000000025]

In [ ]:
np.linspace(1,3,10)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
on=np.ones((2,3,4))

In [ ]:
on

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
on*3+2

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [ ]:
np.empty(1)

array([5.])

In [ ]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.logspace(2,5,10 , base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [94]:
arr=np.random.randn(3,4)  #mean=0 ,sd=1

In [95]:
arr

array([[ 0.63426979,  1.14585852,  1.92284623, -0.49219429],
       [ 0.49065925, -0.29713388,  0.22689358, -0.03907053],
       [-0.23133367, -1.21806347, -1.11322232, -0.56333877]])

In [96]:
import pandas as pd

In [97]:
pd.DataFrame(arr)  

0         1         2         3
0  0.634270  1.145859  1.922846 -0.492194
1  0.490659 -0.297134  0.226894 -0.039071
2 -0.231334 -1.218063 -1.113222 -0.563339

In [98]:
np.random.rand(3,4) #random

array([[0.41164836, 0.12771306, 0.97522643, 0.11662447],
       [0.31862284, 0.97583116, 0.96271854, 0.37735787],
       [0.08580272, 0.57121008, 0.18501674, 0.14976973]])

In [99]:
pd.DataFrame(np.random.randint(1,110,(100,50)))

0   1    2   3    4   5   6   7   8    9   ...   40   41  42  43   44  \
0    86  99   16   6   62  36  46   6  78  108  ...   68    8  13  26   52   
1    82  86   50  30   18  88  95  21  61   73  ...  107   34  34  44   61   
2    45  43  105  88   56  38  50  51  20   97  ...   59   82  29  61   78   
3    16  80   31  69   82  46  83  51  80   99  ...   91   63  32  18   51   
4    70   2   31  82   49  19  50  97  16   87  ...   89   78  30  84   68   
..  ...  ..  ...  ..  ...  ..  ..  ..  ..  ...  ...  ...  ...  ..  ..  ...   
95   24   2   12  45  106  47   3  96   4   37  ...   54   63  55  13   50   
96   81  42    3  67  109  92  40  76  88   33  ...   51   39   9  46  106   
97   41  54   97  57   94  38  80  16  21   62  ...   44   61  92  19   96   
98   96  16   51  47   46  36  99  43  37   28  ...   83   34  28  51   22   
99  105  31   25  70   57  27  77  82  18   58  ...   82  104  91  94   48   

     45  46   47   48   49  
0    98   5   37   19   10  
1    21  48   27   67   83  
2    14  36   24   84  103  
3    63  26  105    6   35  
4    70  96   13   43   13  
..  ...  ..  ...  ...  ...  
95   64  81   59   43  103  
96   84  88   65   40   75  
97   46  32   19   29   36  
98   90  35   26  107    6  
99  109  41   73   64  105  

[100 rows x 50 columns]

In [100]:
arr=np.random.rand(3,4)

In [101]:
arr

array([[0.23820577, 0.11572806, 0.07683912, 0.45199869],
       [0.907009  , 0.9783158 , 0.06839474, 0.86478108],
       [0.32397059, 0.86539332, 0.33458529, 0.08205901]])

In [103]:
arr1=arr.reshape(6,2)

In [104]:
arr1

array([[0.23820577, 0.11572806],
       [0.07683912, 0.45199869],
       [0.907009  , 0.9783158 ],
       [0.06839474, 0.86478108],
       [0.32397059, 0.86539332],
       [0.33458529, 0.08205901]])

In [108]:
arr1[1][1]

0.45199869179786

In [109]:
arr1[1,0]

0.07683912176744123

In [111]:
arr1[2:5,1]

array([0.9783158 , 0.86478108, 0.86539332])

In [113]:
arr=np.random.randint(1,100,(5,5))

In [114]:
arr

array([[91, 10, 30,  5, 49],
       [47,  8, 92, 14, 60],
       [32, 12, 53, 40, 15],
       [19, 35,  7, 63, 35],
       [59, 23, 75, 49, 79]])

In [115]:
arr>50

array([[ True, False, False, False, False],
       [False, False,  True, False,  True],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [ True, False,  True, False,  True]])

In [116]:
arr[arr>50]

array([91, 92, 60, 53, 63, 59, 75, 79])

In [117]:
arr

array([[91, 10, 30,  5, 49],
       [47,  8, 92, 14, 60],
       [32, 12, 53, 40, 15],
       [19, 35,  7, 63, 35],
       [59, 23, 75, 49, 79]])

In [119]:
arr[2:4,[1,2,3]]

array([[12, 53, 40],
       [35,  7, 63]])

In [120]:
arr

array([[91, 10, 30,  5, 49],
       [47,  8, 92, 14, 60],
       [32, 12, 53, 40, 15],
       [19, 35,  7, 63, 35],
       [59, 23, 75, 49, 79]])

In [121]:
arr[0][0]=400

In [122]:
arr

array([[400,  10,  30,   5,  49],
       [ 47,   8,  92,  14,  60],
       [ 32,  12,  53,  40,  15],
       [ 19,  35,   7,  63,  35],
       [ 59,  23,  75,  49,  79]])

In [125]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [126]:
arr1

array([[1, 2, 1],
       [1, 1, 2],
       [2, 1, 1]])

In [127]:
arr2

array([[2, 1, 1],
       [1, 1, 1],
       [2, 2, 1]])

In [128]:
arr1+arr2

array([[3, 3, 2],
       [2, 2, 3],
       [4, 3, 2]])

In [129]:
arr1-arr2

array([[-1,  1,  0],
       [ 0,  0,  1],
       [ 0, -1,  0]])

In [130]:
arr1/arr2

array([[0.5, 2. , 1. ],
       [1. , 1. , 2. ],
       [1. , 0.5, 1. ]])

In [131]:
arr1

array([[1, 2, 1],
       [1, 1, 2],
       [2, 1, 1]])

In [132]:
arr2

array([[2, 1, 1],
       [1, 1, 1],
       [2, 2, 1]])

In [133]:
arr1*arr2

array([[2, 2, 1],
       [1, 1, 2],
       [4, 2, 1]])

In [ ]:
arr1@arr2 #matrix multiplication

array([[6, 5, 4],
       [7, 6, 4],
       [7, 5, 4]])

In [135]:
arr1/0

C:\Users\Ranajit Hazra\AppData\Local\Temp\ipykernel_13308\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [137]:
arr1+100

array([[101, 102, 101],
       [101, 101, 102],
       [102, 101, 101]])

In [138]:
arr1**2

array([[1, 4, 1],
       [1, 1, 4],
       [4, 1, 1]])

In [144]:
#numby-broadcasting
arr=np.zeros((4,4))

In [145]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [140]:
row=np.array([1,2,3,4])

In [146]:
row

array([1, 2, 3, 4])

In [155]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [156]:
col=np.array([[1,2,3,4]])

In [157]:
col

array([[1, 2, 3, 4]])

In [ ]:
col.T 

array([[1],
       [2],
       [3],
       [4]])

In [160]:
col.T + row

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])